version: "3.6"

services:

  tgbot:
    container_name: bot
    build: .
    volumes:
      - .:/src
    command: python app.py
    restart: always
    network_mode: "host"
    env_file:
      - ".env"

  db:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user

    volumes:
      - ./init:/docker-entrypoint-initdb.d

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080