version: "3.3"

services:

  tgbot:
    container_name: bot
    build: .
    volumes:
      - .:/src
    command: python app.py
    restart: always
    network_mode: "host"
    env_file:
      - ".env"