from aiogram.types import ReplyKeyboardMarkup, KeyboardButton

regions = ReplyKeyboardMarkup(
    keyboard=[
        [
            KeyboardButton(text="🔙 Головне меню")
        ],
        [
            KeyboardButton(text="Вся Україна"),
        ],
        [
            KeyboardButton(text="м.Київ"),
        ],
        [
            KeyboardButton(text="Автономна Республіка Крим"),
        ],
        [
            KeyboardButton(text="Вінницька"),
        ],
        [
            KeyboardButton(text="Волинська"),
        ],
        [
            KeyboardButton(text="Дніпропетровська"),
        ],
        [
            KeyboardButton(text="Донецька"),
        ],
        [
            KeyboardButton(text="Житомирська"),
        ],
        [
            KeyboardButton(text="Закарпатська"),
        ],
        [
            KeyboardButton(text="Запорізька"),
        ],
        [
            KeyboardButton(text="Івано-Франківська"),
        ],
        [
            KeyboardButton(text="Київська"),
        ],
        [
            KeyboardButton(text="Кіровоградська"),
        ],
        [
            KeyboardButton(text="Луганська"),
        ],
        [
            KeyboardButton(text="Львівська"),
        ],
        [
            KeyboardButton(text="Миколаївська"),
        ],
        [
            KeyboardButton(text="Одеська"),
        ],
        [
            KeyboardButton(text="Полтавська"),
        ],
        [
            KeyboardButton(text="Рівненська"),
        ],
        [
            KeyboardButton(text="Сумська"),
        ],
        [
            KeyboardButton(text="Тернопільська"),
        ],
        [
            KeyboardButton(text="Харківська"),
        ],
        [
            KeyboardButton(text="Херсонська"),
        ],
        [
            KeyboardButton(text="Хмельницька"),
        ],
        [
            KeyboardButton(text="Черкаська"),
        ],
        [
            KeyboardButton(text="Чернівецька"),
        ],
        [
            KeyboardButton(text="Чернігівська"),
        ],
        [
            KeyboardButton(text="м. Севастополь"),
        ],
    ],
    resize_keyboard=True
)
